### PR TITLE
Many bugfixes: the pretty-sure initiative

### PR DESCRIPTION
**Pull request by mozbugzi**
Yesterday I proposed patches for two bugs from Bugzilla:
- https://bugzilla.mozilla.org/show_bug.cgi?id=1206633
- https://bugzilla.mozilla.org/show_bug.cgi?id=1261971

I thought it could be worthwhile to look for similar bugs, so I grabbed this corpus of 142k JS files: http://www.srl.inf.ethz.ch/js150.php

135k of these can be parsed by Acorn. By comparing the AST before and after prettifying, I found 7 additional bugs that caused issues such as invalid syntax or silent changes in semantics that affected 1354 files. After these fixes, now only 6 files fail and they're corner cases that might not be worth fixing: escaped keywords used as identifiers, certain cases of automatic semicolon insertion, and lack of support in Node for ES6 regexps.

Since some of the fixes depend on each other, I'm making a single pull request with all the fixes. I hope this is OK.

### CODE REVIEW

**Comment by mozbugzi2** [comment]
@jasonLaster Can you look at this?

**Comment by jimblandy** [comment]
@mozbugzi2 This looks fantastic, but just so you know, all Mozillians are flying to Austin TX next week for an all-company meeting, so you may not get an immediate

**Comment by jimblandy** [comment]
Sorry - misclick

**Comment by darkwing** [comment]
@mozbugzi I pushed two fix-up commits (to fix merge issues) to your branch and somehow GitHub closed the PR without the commits; could you resubmit please?

Thank you!  Your work is great!

**Pull request closed without merging**
