### PR TITLE
Fix classes

### PR DESCRIPTION
**Pull request by legnaleurc**
Before:
```javascript
classClassextendsBase{}
```

After:
```javascript
class Class extends Base {
}
```

### CODE REVIEW

**Comment by jasonLaster** [comment]
Thanks @legnaleurc! 

WIll take a look soon

**Comment by darkwing** [comment]
Awesome work @legnaleurc!  I caught one test case that would fail:

```js
{
      name: "Class extension within a function",
      input: "(function() {  class X extends Y { constructor() {} }  })()",
      output: "(function () {\n  class X extends Y {\n    constructor() {\n    }\n  }\n}) ()"
  }
```

With your PR, this case fails due to a missing space between the class name and "extends":

```js
(function () {
  class Xextends Y {
    constructor() {
    }
  }
}) ()
```

The issue can be fixed by removing `stack[stack.length - 1] == undefined` from your `isExtends` function:

```
function isExtends(token, stack) {
    /*
    return stack[stack.length - 1] == undefined
      && token
      && (token.value == "extends");
    */
    return token && (token.value == "extends");
  }
```

Can you tell me why `stack[stack.length - 1] == undefined` is a condition of this function?

We're almost there!  Great work!

**Comment by legnaleurc** [comment]
> Can you tell me why stack[stack.length - 1] == undefined is a condition of this function?

I forgot that classes do not need to be declared at top-level.
The failed test has been added into this branch. Thanks!

**Comment by darkwing** [comment]
One last nit @legnaleurc ; could you remove the "()" from this line?

`(token.value == "extends")`

Then I can merge! :) . Great work!

**Comment by legnaleurc** [comment]
@darkwing Done :)

**Pull request merged**
